# Generated by Django 2.2.7 on 2019-11-19 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testmethod',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_methods', to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to='contenttypes.ContentType'),
        ),
    ]
