# Generated by Django 2.2.9 on 2020-01-06 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('data_tests', '0002_auto_20191119_1055'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testmethod',
            unique_together={('content_type', 'method_name')},
        ),
    ]
